apiVersion: firestarter.dev/v1
kind: FirestarterGithubGroup
metadata:
  name: group-z
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  uuid: abb9b0de-d366-4522-947a-43c898d687e9
  type: business-unit
  profile:
    displayName: testGroupa
    email: fooa@foo.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
  members: []
