apiVersion: firestarter.dev/v1
kind: FirestarterGithubRepository
metadata:
  name: test-demo-z
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    backstage.io/source-location: url:https://github.com/prefapp/catalog
    github.com/project-slug: org/component_z
spec:
  uuid: 092dc17f-fc1c-4f89-9472-28497e11b08c
  type: service
  lifecycle: production
  owner: group-z
  platformOwner: group-z
  maintainedBy:
    - "group-z"
  provisioner:
    org: prefapp
    orgVisibility: false
    orgContributions: false
    technology:
      stack: node
      version: "18"
    repo:
      visibility: private
      ciSystem: github
      defaultBranch: main
      branchStrategy: none
      branches:
        protections:
          override:
            is_override: false
            number_reviewer: null
    features: []
  system: system_a
