name: CDK8s render

on:
  pull_request:
    paths:
      - "claims/**.yaml"

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main_state

      - name: Checkout new branch (PR head ref)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: desired_state

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: "json"
          working-directory: desired_state
          filters: |
            changed:
              - 'claims/**'

      - name: Debug
        run: |
          echo "Changed files: ${{ steps.filter.outputs.changed_files }}"
